name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: '1.25.0'

jobs:
  validate:
    name: Validate Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          
      - name: Verify go.mod and go.sum
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum

      - name: Validate .env_example
        run: |
          if [ ! -f ".env_example" ]; then
            echo ".env_example not found!"
            exit 1
          fi
          echo ".env_example file validated successfully"